### ISSUE TITLE
Issue running command knex seed:run

### ISSUE THREAD

**Issue by grawlinson** [gmcdowell/bookshelf-demo#1]
Hello, when I try and run the command `knex seed:run`, the program spits this out and hangs.

`  { command: 'INSERT',
    rowCount: 1,
    oid: 0,
    rows: [],
    fields: [],
    _parsers: [],
    RowCtor: null,
    rowAsArray: false,
    _getTypeParser: [Function: bound ] },
  { command: 'INSERT',
    rowCount: 1,
    oid: 0,
    rows: [],
    fields: [],
    _parsers: [],
    RowCtor: null,
    rowAsArray: false,
    _getTypeParser: [Function: bound ] },
  { command: 'INSERT',
    rowCount: 1,
    oid: 0,
    rows: [],
    fields: [],
    _parsers: [],
    RowCtor: null,
    rowAsArray: false,
    _getTypeParser: [Function: bound ] },
  { command: 'INSERT',
    rowCount: 1,
    oid: 0,
    rows: [],
    fields: [],
    _parsers: [],
    RowCtor: null,
    rowAsArray: false,
    _getTypeParser: [Function: bound ] },
  { command: 'INSERT',
    rowCount: 1,
    oid: 0,
    rows: [],
    fields: [],
    _parsers: [],
    RowCtor: null,
    rowAsArray: false,
    _getTypeParser: [Function: bound ] },
  { command: 'INSERT',
    rowCount: 1,
    oid: 0,
    rows: [],
    fields: [],
    _parsers: [],
    RowCtor: null,
    rowAsArray: false,
    _getTypeParser: [Function: bound ] },
  { command: 'INSERT',
    rowCount: 1,
    oid: 0,
    rows: [],
    fields: [],
    _parsers: [],
    RowCtor: null,
    rowAsArray: false,
    _getTypeParser: [Function: bound ] },
  { command: 'INSERT',
    rowCount: 1,
    oid: 0,
    rows: [],
    fields: [],
    _parsers: [],
    RowCtor: null,
    rowAsArray: false,
    _getTypeParser: [Function: bound ] },
  { command: 'INSERT',
    rowCount: 1,
    oid: 0,
    rows: [],
    fields: [],
    _parsers: [],
    RowCtor: null,
    rowAsArray: false,
    _getTypeParser: [Function: bound ] },
  { command: 'INSERT',
    rowCount: 1,
    oid: 0,
    rows: [],
    fields: [],
    _parsers: [],
    RowCtor: null,
    rowAsArray: false,
    _getTypeParser: [Function: bound ] },
  { command: 'INSERT',
    rowCount: 1,
    oid: 0,
    rows: [],
    fields: [],
    _parsers: [],
    RowCtor: null,
    rowAsArray: false,
    _getTypeParser: [Function: bound ] } ]
[ { command: 'INSERT',
    rowCount: 1,
    oid: 0,
    rows: [],
    fields: [],
    _parsers: [],
    RowCtor: null,
    rowAsArray: false,
    _getTypeParser: [Function: bound ] },
  { command: 'INSERT',
    rowCount: 1,
    oid: 0,
    rows: [],
    fields: [],
    _parsers: [],
    RowCtor: null,
    rowAsArray: false,
    _getTypeParser: [Function: bound ] },
  { command: 'INSERT',
    rowCount: 1,
    oid: 0,
    rows: [],
    fields: [],
    _parsers: [],
    RowCtor: null,
    rowAsArray: false,
    _getTypeParser: [Function: bound ] },
  { command: 'INSERT',
    rowCount: 1,
    oid: 0,
    rows: [],
    fields: [],
    _parsers: [],
    RowCtor: null,
    rowAsArray: false,
    _getTypeParser: [Function: bound ] },
  { command: 'INSERT',
    rowCount: 1,
    oid: 0,
    rows: [],
    fields: [],
    _parsers: [],
    RowCtor: null,
    rowAsArray: false,
    _getTypeParser: [Function: bound ] },
  { command: 'INSERT',
    rowCount: 1,
    oid: 0,
    rows: [],
    fields: [],
    _parsers: [],
    RowCtor: null,
    rowAsArray: false,
    _getTypeParser: [Function: bound ] },
  { command: 'INSERT',
    rowCount: 1,
    oid: 0,
    rows: [],
    fields: [],
    _parsers: [],
    RowCtor: null,
    rowAsArray: false,
    _getTypeParser: [Function: bound ] },
  { command: 'INSERT',
    rowCount: 1,
    oid: 0,
    rows: [],
    fields: [],
    _parsers: [],
    RowCtor: null,
    rowAsArray: false,
    _getTypeParser: [Function: bound ] },
  { command: 'INSERT',
    rowCount: 1,
    oid: 0,
    rows: [],
    fields: [],
    _parsers: [],
    RowCtor: null,
    rowAsArray: false,
    _getTypeParser: [Function: bound ] },
  { command: 'INSERT',
    rowCount: 1,
    oid: 0,
    rows: [],
    fields: [],
    _parsers: [],
    RowCtor: null,
    rowAsArray: false,
    _getTypeParser: [Function: bound ] },
  { command: 'INSERT',
    rowCount: 1,
    oid: 0,
    rows: [],
    fields: [],
    _parsers: [],
    RowCtor: null,
    rowAsArray: false,
    _getTypeParser: [Function: bound ] },
  { command: 'INSERT',
    rowCount: 1,
    oid: 0,
    rows: [],
    fields: [],
    _parsers: [],
    RowCtor: null,
    rowAsArray: false,
    _getTypeParser: [Function: bound ] },
  { command: 'INSERT',
    rowCount: 1,
    oid: 0,
    rows: [],
    fields: [],
    _parsers: [],
    RowCtor: null,
    rowAsArray: false,
    _getTypeParser: [Function: bound ] },
  { command: 'INSERT',
    rowCount: 1,
    oid: 0,
    rows: [],
    fields: [],
    _parsers: [],
    RowCtor: null,
    rowAsArray: false,
    _getTypeParser: [Function: bound ] },
  { command: 'INSERT',
    rowCount: 1,
    oid: 0,
    rows: [],
    fields: [],
    _parsers: [],
    RowCtor: null,
    rowAsArray: false,
    _getTypeParser: [Function: bound ] },
  { command: 'INSERT',
    rowCount: 1,
    oid: 0,
    rows: [],
    fields: [],
    _parsers: [],
    RowCtor: null,
    rowAsArray: false,
    _getTypeParser: [Function: bound ] },
  { command: 'INSERT',
    rowCount: 1,
    oid: 0,
    rows: [],
    fields: [],
    _parsers: [],
    RowCtor: null,
    rowAsArray: false,
    _getTypeParser: [Function: bound ] },
  { command: 'INSERT',
    rowCount: 1,
    oid: 0,
    rows: [],
    fields: [],
    _parsers: [],
    RowCtor: null,
    rowAsArray: false,
    _getTypeParser: [Function: bound ] },
  { command: 'INSERT',
    rowCount: 1,
    oid: 0,
    rows: [],
    fields: [],
    _parsers: [],
    RowCtor: null,
    rowAsArray: false,
    _getTypeParser: [Function: bound ] },
  { command: 'INSERT',
    rowCount: 1,
    oid: 0,
    rows: [],
    fields: [],
    _parsers: [],
    RowCtor: null,
    rowAsArray: false,
    _getTypeParser: [Function: bound ] },
  { command: 'INSERT',
    rowCount: 1,
    oid: 0,
    rows: [],
    fields: [],
    _parsers: [],
    RowCtor: null,
    rowAsArray: false,
    _getTypeParser: [Function: bound ] },
  { command: 'INSERT',
    rowCount: 1,
    oid: 0,
    rows: [],
    fields: [],
    _parsers: [],
    RowCtor: null,
    rowAsArray: false,
    _getTypeParser: [Function: bound ] },
  { command: 'INSERT',
    rowCount: 1,
    oid: 0,
    rows: [],
    fields: [],
    _parsers: [],
    RowCtor: null,
    rowAsArray: false,
    _getTypeParser: [Function: bound ] },
  { command: 'INSERT',
    rowCount: 1,
    oid: 0,
    rows: [],
    fields: [],
    _parsers: [],
    RowCtor: null,
    rowAsArray: false,
    _getTypeParser: [Function: bound ] },
  { command: 'INSERT',
    rowCount: 1,
    oid: 0,
    rows: [],
    fields: [],
    _parsers: [],
    RowCtor: null,
    rowAsArray: false,
    _getTypeParser: [Function: bound ] },
  { command: 'INSERT',
    rowCount: 1,
    oid: 0,
    rows: [],
    fields: [],
    _parsers: [],
    RowCtor: null,
    rowAsArray: false,
    _getTypeParser: [Function: bound ] },
  { command: 'INSERT',
    rowCount: 1,
    oid: 0,
    rows: [],
    fields: [],
    _parsers: [],
    RowCtor: null,
    rowAsArray: false,
    _getTypeParser: [Function: bound ] },
  { command: 'INSERT',
    rowCount: 1,
    oid: 0,
    rows: [],
    fields: [],
    _parsers: [],
    RowCtor: null,
    rowAsArray: false,
    _getTypeParser: [Function: bound ] },
  { command: 'INSERT',
    rowCount: 1,
    oid: 0,
    rows: [],
    fields: [],
    _parsers: [],
    RowCtor: null,
    rowAsArray: false,
    _getTypeParser: [Function: bound ] },
  { command: 'INSERT',
    rowCount: 1,
    oid: 0,
    rows: [],
    fields: [],
    _parsers: [],
    RowCtor: null,
    rowAsArray: false,
    _getTypeParser: [Function: bound ] },
  { command: 'INSERT',
    rowCount: 1,
    oid: 0,
    rows: [],
    fields: [],
    _parsers: [],
    RowCtor: null,
    rowAsArray: false,
    _getTypeParser: [Function: bound ] },
  { command: 'INSERT',
    rowCount: 1,
    oid: 0,
    rows: [],
    fields: [],
    _parsers: [],
    RowCtor: null,
    rowAsArray: false,
    _getTypeParser: [Function: bound ] },
  { command: 'INSERT',
    rowCount: 1,
    oid: 0,
    rows: [],
    fields: [],
    _parsers: [],
    RowCtor: null,
    rowAsArray: false,
    _getTypeParser: [Function: bound ] },
  { command: 'INSERT',
    rowCount: 1,
    oid: 0,
    rows: [],
    fields: [],
    _parsers: [],
    RowCtor: null,
    rowAsArray: false,
    _getTypeParser: [Function: bound ] },
  { command: 'INSERT',
    rowCount: 1,
    oid: 0,
    rows: [],
    fields: [],
    _parsers: [],
    RowCtor: null,
    rowAsArray: false,
    _getTypeParser: [Function: bound ] },
  { command: 'INSERT',
    rowCount: 1,
    oid: 0,
    rows: [],
    fields: [],
    _parsers: [],
    RowCtor: null,
    rowAsArray: false,
    _getTypeParser: [Function: bound ] },
  { command: 'INSERT',
    rowCount: 1,
    oid: 0,
    rows: [],
    fields: [],
    _parsers: [],
    RowCtor: null,
    rowAsArray: false,
    _getTypeParser: [Function: bound ] },
  { command: 'INSERT',
    rowCount: 1,
    oid: 0,
    rows: [],
    fields: [],
    _parsers: [],
    RowCtor: null,
    rowAsArray: false,
    _getTypeParser: [Function: bound ] },
  { command: 'INSERT',
    rowCount: 1,
    oid: 0,
    rows: [],
    fields: [],
    _parsers: [],
    RowCtor: null,
    rowAsArray: false,
    _getTypeParser: [Function: bound ] },
  { command: 'INSERT',
    rowCount: 1,
    oid: 0,
    rows: [],
    fields: [],
    _parsers: [],
    RowCtor: null,
    rowAsArray: false,
    _getTypeParser: [Function: bound ] },
  { command: 'INSERT',
    rowCount: 1,
    oid: 0,
    rows: [],
    fields: [],
    _parsers: [],
    RowCtor: null,
    rowAsArray: false,
    _getTypeParser: [Function: bound ] },
  { command: 'INSERT',
    rowCount: 1,
    oid: 0,
    rows: [],
    fields: [],
    _parsers: [],
    RowCtor: null,
    rowAsArray: false,
    _getTypeParser: [Function: bound ] },
  { command: 'INSERT',
    rowCount: 1,
    oid: 0,
    rows: [],
    fields: [],
    _parsers: [],
    RowCtor: null,
    rowAsArray: false,
    _getTypeParser: [Function: bound ] },
  { command: 'INSERT',
    rowCount: 1,
    oid: 0,
    rows: [],
    fields: [],
    _parsers: [],
    RowCtor: null,
    rowAsArray: false,
    _getTypeParser: [Function: bound ] },
  { command: 'INSERT',
    rowCount: 1,
    oid: 0,
    rows: [],
    fields: [],
    _parsers: [],
    RowCtor: null,
    rowAsArray: false,
    _getTypeParser: [Function: bound ] },
  { command: 'INSERT',
    rowCount: 1,
    oid: 0,
    rows: [],
    fields: [],
    _parsers: [],
    RowCtor: null,
    rowAsArray: false,
    _getTypeParser: [Function: bound ] },
  { command: 'INSERT',
    rowCount: 1,
    oid: 0,
    rows: [],
    fields: [],
    _parsers: [],
    RowCtor: null,
    rowAsArray: false,
    _getTypeParser: [Function: bound ] },
  { command: 'INSERT',
    rowCount: 1,
    oid: 0,
    rows: [],
    fields: [],
    _parsers: [],
    RowCtor: null,
    rowAsArray: false,
    _getTypeParser: [Function: bound ] },
  { command: 'INSERT',
    rowCount: 1,
    oid: 0,
    rows: [],
    fields: [],
    _parsers: [],
    RowCtor: null,
    rowAsArray: false,
    _getTypeParser: [Function: bound ] },
  { command: 'INSERT',
    rowCount: 1,
    oid: 0,
    rows: [],
    fields: [],
    _parsers: [],
    RowCtor: null,
    rowAsArray: false,
    _getTypeParser: [Function: bound ] },
  { command: 'INSERT',
    rowCount: 1,
    oid: 0,
    rows: [],
    fields: [],
    _parsers: [],
    RowCtor: null,
    rowAsArray: false,
    _getTypeParser: [Function: bound ] },
  { command: 'INSERT',
    rowCount: 1,
    oid: 0,
    rows: [],
    fields: [],
    _parsers: [],
    RowCtor: null,
    rowAsArray: false,
    _getTypeParser: [Function: bound ] },
  { command: 'INSERT',
    rowCount: 1,
    oid: 0,
    rows: [],
    fields: [],
    _parsers: [],
    RowCtor: null,
    rowAsArray: false,
    _getTypeParser: [Function: bound ] },
  { command: 'INSERT',
    rowCount: 1,
    oid: 0,
    rows: [],
    fields: [],
    _parsers: [],
    RowCtor: null,
    rowAsArray: false,
    _getTypeParser: [Function: bound ] },
  { command: 'INSERT',
    rowCount: 1,
    oid: 0,
    rows: [],
    fields: [],
    _parsers: [],
    RowCtor: null,
    rowAsArray: false,
    _getTypeParser: [Function: bound ] },
  { command: 'INSERT',
    rowCount: 1,
    oid: 0,
    rows: [],
    fields: [],
    _parsers: [],
    RowCtor: null,
    rowAsArray: false,
    _getTypeParser: [Function: bound ] },
  { command: 'INSERT',
    rowCount: 1,
    oid: 0,
    rows: [],
    fields: [],
    _parsers: [],
    RowCtor: null,
    rowAsArray: false,
    _getTypeParser: [Function: bound ] },
  { command: 'INSERT',
    rowCount: 1,
    oid: 0,
    rows: [],
    fields: [],
    _parsers: [],
    RowCtor: null,
    rowAsArray: false,
    _getTypeParser: [Function: bound ] },
  { command: 'INSERT',
    rowCount: 1,
    oid: 0,
    rows: [],
    fields: [],
    _parsers: [],
    RowCtor: null,
    rowAsArray: false,
    _getTypeParser: [Function: bound ] },
  { command: 'INSERT',
    rowCount: 1,
    oid: 0,
    rows: [],
    fields: [],
    _parsers: [],
    RowCtor: null,
    rowAsArray: false,
    _getTypeParser: [Function: bound ] },
  { command: 'INSERT',
    rowCount: 1,
    oid: 0,
    rows: [],
    fields: [],
    _parsers: [],
    RowCtor: null,
    rowAsArray: false,
    _getTypeParser: [Function: bound ] },
  { command: 'INSERT',
    rowCount: 1,
    oid: 0,
    rows: [],
    fields: [],
    _parsers: [],
    RowCtor: null,
    rowAsArray: false,
    _getTypeParser: [Function: bound ] },
  { command: 'INSERT',
    rowCount: 1,
    oid: 0,
    rows: [],
    fields: [],
    _parsers: [],
    RowCtor: null,
    rowAsArray: false,
    _getTypeParser: [Function: bound ] },
  { command: 'INSERT',
    rowCount: 1,
    oid: 0,
    rows: [],
    fields: [],
    _parsers: [],
    RowCtor: null,
    rowAsArray: false,
    _getTypeParser: [Function: bound ] },
  { command: 'INSERT',
    rowCount: 1,
    oid: 0,
    rows: [],
    fields: [],
    _parsers: [],
    RowCtor: null,
    rowAsArray: false,
    _getTypeParser: [Function: bound ] },
  { command: 'INSERT',
    rowCount: 1,
    oid: 0,
    rows: [],
    fields: [],
    _parsers: [],
    RowCtor: null,
    rowAsArray: false,
    _getTypeParser: [Function: bound ] },
  { command: 'INSERT',
    rowCount: 1,
    oid: 0,
    rows: [],
    fields: [],
    _parsers: [],
    RowCtor: null,
    rowAsArray: false,
    _getTypeParser: [Function: bound ] },
  { command: 'INSERT',
    rowCount: 1,
    oid: 0,
    rows: [],
    fields: [],
    _parsers: [],
    RowCtor: null,
    rowAsArray: false,
    _getTypeParser: [Function: bound ] },
  { command: 'INSERT',
    rowCount: 1,
    oid: 0,
    rows: [],
    fields: [],
    _parsers: [],
    RowCtor: null,
    rowAsArray: false,
    _getTypeParser: [Function: bound ] },
  { command: 'INSERT',
    rowCount: 1,
    oid: 0,
    rows: [],
    fields: [],
    _parsers: [],
    RowCtor: null,
    rowAsArray: false,
    _getTypeParser: [Function: bound ] },
  { command: 'INSERT',
    rowCount: 1,
    oid: 0,
    rows: [],
    fields: [],
    _parsers: [],
    RowCtor: null,
    rowAsArray: false,
    _getTypeParser: [Function: bound ] },
  { command: 'INSERT',
    rowCount: 1,
    oid: 0,
    rows: [],
    fields: [],
    _parsers: [],
    RowCtor: null,
    rowAsArray: false,
    _getTypeParser: [Function: bound ] },
  { command: 'INSERT',
    rowCount: 1,
    oid: 0,
    rows: [],
    fields: [],
    _parsers: [],
    RowCtor: null,
    rowAsArray: false,
    _getTypeParser: [Function: bound ] },
  { command: 'INSERT',
    rowCount: 1,
    oid: 0,
    rows: [],
    fields: [],
    _parsers: [],
    RowCtor: null,
    rowAsArray: false,
    _getTypeParser: [Function: bound ] },
  { command: 'INSERT',
    rowCount: 1,
    oid: 0,
    rows: [],
    fields: [],
    _parsers: [],
    RowCtor: null,
    rowAsArray: false,
    _getTypeParser: [Function: bound ] },
  { command: 'INSERT',
    rowCount: 1,
    oid: 0,
    rows: [],
    fields: [],
    _parsers: [],
    RowCtor: null,
    rowAsArray: false,
    _getTypeParser: [Function: bound ] },
  { command: 'INSERT',
    rowCount: 1,
    oid: 0,
    rows: [],
    fields: [],
    _parsers: [],
    RowCtor: null,
    rowAsArray: false,
    _getTypeParser: [Function: bound ] },
  { command: 'INSERT',
    rowCount: 1,
    oid: 0,
    rows: [],
    fields: [],
    _parsers: [],
    RowCtor: null,
    rowAsArray: false,
    _getTypeParser: [Function: bound ] },
  { command: 'INSERT',
    rowCount: 1,
    oid: 0,
    rows: [],
    fields: [],
    _parsers: [],
    RowCtor: null,
    rowAsArray: false,
    _getTypeParser: [Function: bound ] },
  { command: 'INSERT',
    rowCount: 1,
    oid: 0,
    rows: [],
    fields: [],
    _parsers: [],
    RowCtor: null,
    rowAsArray: false,
    _getTypeParser: [Function: bound ] },
  { command: 'INSERT',
    rowCount: 1,
    oid: 0,
    rows: [],
    fields: [],
    _parsers: [],
    RowCtor: null,
    rowAsArray: false,
    _getTypeParser: [Function: bound ] },
  { command: 'INSERT',
    rowCount: 1,
    oid: 0,
    rows: [],
    fields: [],
    _parsers: [],
    RowCtor: null,
    rowAsArray: false,
    _getTypeParser: [Function: bound ] },
  { command: 'INSERT',
    rowCount: 1,
    oid: 0,
    rows: [],
    fields: [],
    _parsers: [],
    RowCtor: null,
    rowAsArray: false,
    _getTypeParser: [Function: bound ] },
  { command: 'INSERT',
    rowCount: 1,
    oid: 0,
    rows: [],
    fields: [],
    _parsers: [],
    RowCtor: null,
    rowAsArray: false,
    _getTypeParser: [Function: bound ] },
  { command: 'INSERT',
    rowCount: 1,
    oid: 0,
    rows: [],
    fields: [],
    _parsers: [],
    RowCtor: null,
    rowAsArray: false,
    _getTypeParser: [Function: bound ] },
  { command: 'INSERT',
    rowCount: 1,
    oid: 0,
    rows: [],
    fields: [],
    _parsers: [],
    RowCtor: null,
    rowAsArray: false,
    _getTypeParser: [Function: bound ] },
  { command: 'INSERT',
    rowCount: 1,
    oid: 0,
    rows: [],
    fields: [],
    _parsers: [],
    RowCtor: null,
    rowAsArray: false,
    _getTypeParser: [Function: bound ] },
  { command: 'INSERT',
    rowCount: 1,
    oid: 0,
    rows: [],
    fields: [],
    _parsers: [],
    RowCtor: null,
    rowAsArray: false,
    _getTypeParser: [Function: bound ] },
  { command: 'INSERT',
    rowCount: 1,
    oid: 0,
    rows: [],
    fields: [],
    _parsers: [],
    RowCtor: null,
    rowAsArray: false,
    _getTypeParser: [Function: bound ] },
  { command: 'INSERT',
    rowCount: 1,
    oid: 0,
    rows: [],
    fields: [],
    _parsers: [],
    RowCtor: null,
    rowAsArray: false,
    _getTypeParser: [Function: bound ] },
  { command: 'INSERT',
    rowCount: 1,
    oid: 0,
    rows: [],
    fields: [],
    _parsers: [],
    RowCtor: null,
    rowAsArray: false,
    _getTypeParser: [Function: bound ] },
  { command: 'INSERT',
    rowCount: 1,
    oid: 0,
    rows: [],
    fields: [],
    _parsers: [],
    RowCtor: null,
    rowAsArray: false,
    _getTypeParser: [Function: bound ] },
  { command: 'INSERT',
    rowCount: 1,
    oid: 0,
    rows: [],
    fields: [],
    _parsers: [],
    RowCtor: null,
    rowAsArray: false,
    _getTypeParser: [Function: bound ] },
  { command: 'INSERT',
    rowCount: 1,
    oid: 0,
    rows: [],
    fields: [],
    _parsers: [],
    RowCtor: null,
    rowAsArray: false,
    _getTypeParser: [Function: bound ] },
  { command: 'INSERT',
    rowCount: 1,
    oid: 0,
    rows: [],
    fields: [],
    _parsers: [],
    RowCtor: null,
    rowAsArray: false,
    _getTypeParser: [Function: bound ] },
  { command: 'INSERT',
    rowCount: 1,
    oid: 0,
    rows: [],
    fields: [],
    _parsers: [],
    RowCtor: null,
    rowAsArray: false,
    _getTypeParser: [Function: bound ] },
  { command: 'INSERT',
    rowCount: 1,
    oid: 0,
    rows: [],
    fields: [],
    _parsers: [],
    RowCtor: null,
    rowAsArray: false,
    _getTypeParser: [Function: bound ] },
  { command: 'INSERT',
    rowCount: 1,
    oid: 0,
    rows: [],
    fields: [],
    _parsers: [],
    RowCtor: null,
    rowAsArray: false,
    _getTypeParser: [Function: bound ] },
  { command: 'INSERT',
    rowCount: 1,
    oid: 0,
    rows: [],
    fields: [],
    _parsers: [],
    RowCtor: null,
    rowAsArray: false,
    _getTypeParser: [Function: bound ] },
  { command: 'INSERT',
    rowCount: 1,
    oid: 0,
    rows: [],
    fields: [],
    _parsers: [],
    RowCtor: null,
    rowAsArray: false,
    _getTypeParser: [Function: bound ] } ]`

**Comment by gmcdowell** [comment]
Hi grawlinson,

That output is expected, but I suspect that the hanging is the result of running out of available memory.
Try removing all but one of the seed files (/seeds/00x-xxxxxxx.js), leaving the data directory in place, and see if you can run it. Then incrementally add the files back in.

**Comment by grawlinson** [comment]
The first two work, but after I add a third, it hangs after this line:
Using environment: development
